/*
Nome: Pedro Vitor Melo Bitencourt
Matrícula: 20213001540
*/
package visao;
import javax.swing.JOptionPane;
import newpackage.JogoDaVelha;

public class JanelaDoJogo extends javax.swing.JFrame {
    public static boolean jaTeveAPrimeiraJogada;
    public static JogoDaVelha bolinha;
    public static JogoDaVelha x;
    public static boolean jaAcabouAPartida;
    public JanelaDoJogo() {
        initComponents();
        x = new JogoDaVelha(false);
        bolinha = new JogoDaVelha(true);
        jButton12.setSelected(true);
        this.setTitle("Jogo da Velha");
        jaTeveAPrimeiraJogada = false;
        jaAcabouAPartida = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        jToggleButton3.setText("jToggleButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escolha a sua peça e clique na posição desejada");

        jButton1.setText("Limpar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setText("X");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setText("O");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            jaTeveAPrimeiraJogada = true;
        }
        if(jButton6.getText().equals("") && !jaAcabouAPartida){
            if(jButton12.isSelected()){
                x.adicionarPosicao(2, 0);
                jButton6.setText("X");
                jButton12.setSelected(false);
                jButton13.setSelected(true);
            }
            else{
                bolinha.adicionarPosicao(2, 0);
                jButton6.setText("O");
                jButton12.setSelected(true);
                jButton13.setSelected(false);
            }
        }
        if(x.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 1 (X) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if(bolinha.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 2 (O) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if((!x.verificarSeGanhou()) && (!bolinha.verificarSeGanhou()) && (!jButton5.getText().equals("")) && (!jButton4.getText().equals(""))
                && (!jButton3.getText().equals("")) && (!jButton11.getText().equals("")) && (!jButton10.getText().equals(""))
                && (!jButton9.getText().equals("")) && (!jButton8.getText().equals("")) && (!jButton7.getText().equals(""))
                && (!jButton6.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "EMPATOU!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            x = new JogoDaVelha(false);
            bolinha = new JogoDaVelha(true);
            jButton12.setSelected(true);
            if(jButton13.isSelected() == true){
                jButton13.setSelected(false);
            }
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            x = new JogoDaVelha(false);
            bolinha = new JogoDaVelha(true);
            if(jButton12.isSelected()){
                jButton12.setSelected(false);
            }
        }
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            jaTeveAPrimeiraJogada = true;
        }
        if(jButton7.getText().equals("") && !jaAcabouAPartida){
            if(jButton12.isSelected()){
                x.adicionarPosicao(2, 1);
                jButton7.setText("X");
                jButton12.setSelected(false);
                jButton13.setSelected(true);
            }
            else{
                bolinha.adicionarPosicao(2, 1);
                jButton7.setText("O");
                jButton12.setSelected(true);
                jButton13.setSelected(false);    
            }
        }
        
        if(x.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 1 (X) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if(bolinha.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 2 (O) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if((!x.verificarSeGanhou()) && (!bolinha.verificarSeGanhou()) && (!jButton5.getText().equals("")) && (!jButton4.getText().equals(""))
                && (!jButton3.getText().equals("")) && (!jButton11.getText().equals("")) && (!jButton10.getText().equals(""))
                && (!jButton9.getText().equals("")) && (!jButton8.getText().equals("")) && (!jButton7.getText().equals(""))
                && (!jButton6.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "EMPATOU!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            jaTeveAPrimeiraJogada = true;
        }
        if(jButton8.getText().equals("")){
            if(jButton12.isSelected()){
                x.adicionarPosicao(2, 2);
                jButton8.setText("X");
                jButton12.setSelected(false);
                jButton13.setSelected(true);
            }
            else{
                bolinha.adicionarPosicao(2, 2);
                jButton8.setText("O");
                jButton12.setSelected(true);
                jButton13.setSelected(false); 
            }
        }
        else{
            //Exceção
        }
        if(x.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 1 (X) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if(bolinha.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 2 (O) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if((!x.verificarSeGanhou()) && (!bolinha.verificarSeGanhou()) && (!jButton5.getText().equals("")) && (!jButton4.getText().equals(""))
                && (!jButton3.getText().equals("")) && (!jButton11.getText().equals("")) && (!jButton10.getText().equals(""))
                && (!jButton9.getText().equals("")) && (!jButton8.getText().equals("")) && (!jButton7.getText().equals(""))
                && (!jButton6.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "EMPATOU!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            jaTeveAPrimeiraJogada = true;
        }
        if(jButton9.getText().equals("") && !jaAcabouAPartida){
            if(jButton12.isSelected()){
                x.adicionarPosicao(1, 0);
                jButton9.setText("X");
                jButton12.setSelected(false);
                jButton13.setSelected(true);
            }
            else{
                bolinha.adicionarPosicao(1, 0);
                jButton9.setText("O");
                jButton12.setSelected(true);
                jButton13.setSelected(false);
            }
        }
        if(x.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 1 (X) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if(bolinha.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 2 (O) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if((!x.verificarSeGanhou()) && (!bolinha.verificarSeGanhou()) && (!jButton5.getText().equals("")) && (!jButton4.getText().equals(""))
                && (!jButton3.getText().equals("")) && (!jButton11.getText().equals("")) && (!jButton10.getText().equals(""))
                && (!jButton9.getText().equals("")) && (!jButton8.getText().equals("")) && (!jButton7.getText().equals(""))
                && (!jButton6.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "EMPATOU!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            jaTeveAPrimeiraJogada = true;
        }
        if(jButton10.getText().equals("") && !jaAcabouAPartida){
            if(jButton12.isSelected()){
                x.adicionarPosicao(1, 1);
                jButton10.setText("X");
                jButton12.setSelected(false);
                jButton13.setSelected(true);
            }
            else{
                bolinha.adicionarPosicao(1, 1);
                jButton10.setText("O");
                jButton12.setSelected(true);
                jButton13.setSelected(false);
            }
        }
        if(x.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 1 (X) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if(bolinha.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 2 (O) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if((!x.verificarSeGanhou()) && (!bolinha.verificarSeGanhou()) && (!jButton5.getText().equals("")) && (!jButton4.getText().equals(""))
                && (!jButton3.getText().equals("")) && (!jButton11.getText().equals("")) && (!jButton10.getText().equals(""))
                && (!jButton9.getText().equals("")) && (!jButton8.getText().equals("")) && (!jButton7.getText().equals(""))
                && (!jButton6.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "EMPATOU!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            jaTeveAPrimeiraJogada = true;
        }
        if(jButton11.getText().equals("") && !jaAcabouAPartida){
            if(jButton12.isSelected()){
                x.adicionarPosicao(1, 2);
                jButton11.setText("X");
                jButton12.setSelected(false);
                jButton13.setSelected(true);
            }
            else{
                bolinha.adicionarPosicao(1, 2);
                jButton11.setText("O");
                jButton12.setSelected(true);
                jButton13.setSelected(false);
            }
        }
        if(x.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 1 (X) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if(bolinha.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 2 (O) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if((!x.verificarSeGanhou()) && (!bolinha.verificarSeGanhou()) && (!jButton5.getText().equals("")) && (!jButton4.getText().equals(""))
                && (!jButton3.getText().equals("")) && (!jButton11.getText().equals("")) && (!jButton10.getText().equals(""))
                && (!jButton9.getText().equals("")) && (!jButton8.getText().equals("")) && (!jButton7.getText().equals(""))
                && (!jButton6.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "EMPATOU!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            jaTeveAPrimeiraJogada = true;
        }
        if(jButton3.getText().equals("") && !jaAcabouAPartida){
            if(jButton12.isSelected()){
                x.adicionarPosicao(0, 0);
                jButton3.setText("X");
                jButton12.setSelected(false);
                jButton13.setSelected(true);
            }
            else{
                bolinha.adicionarPosicao(0, 0);
                jButton3.setText("O");
                jButton12.setSelected(true);
                jButton13.setSelected(false);
            }
        }
        if(x.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 1 (X) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if(bolinha.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 2 (O) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if((!x.verificarSeGanhou()) && (!bolinha.verificarSeGanhou()) && (!jButton5.getText().equals("")) && (!jButton4.getText().equals(""))
                && (!jButton3.getText().equals("")) && (!jButton11.getText().equals("")) && (!jButton10.getText().equals(""))
                && (!jButton9.getText().equals("")) && (!jButton8.getText().equals("")) && (!jButton7.getText().equals(""))
                && (!jButton6.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "EMPATOU!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            jaTeveAPrimeiraJogada = true;
        }
        if(jButton4.getText().equals("") && !jaAcabouAPartida){
            if(jButton12.isSelected()){
                x.adicionarPosicao(0, 1);
                jButton4.setText("X");
                jButton12.setSelected(false);
                jButton13.setSelected(true);
            }
            else{
                bolinha.adicionarPosicao(0, 1);
                jButton4.setText("O");
                jButton12.setSelected(true);
                jButton13.setSelected(false);
            }
        }
        if(x.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 1 (X) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if(bolinha.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 2 (O) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if((!x.verificarSeGanhou()) && (!bolinha.verificarSeGanhou()) && (!jButton5.getText().equals("")) && (!jButton4.getText().equals(""))
                && (!jButton3.getText().equals("")) && (!jButton11.getText().equals("")) && (!jButton10.getText().equals(""))
                && (!jButton9.getText().equals("")) && (!jButton8.getText().equals("")) && (!jButton7.getText().equals(""))
                && (!jButton6.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "EMPATOU!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        if(jaTeveAPrimeiraJogada == false){
            jaTeveAPrimeiraJogada = true;
        }
        if(jButton5.getText().equals("") && !jaAcabouAPartida){
            if(jButton12.isSelected()){
                x.adicionarPosicao(0, 2);
                jButton5.setText("X");
                jButton12.setSelected(false);
                jButton13.setSelected(true);
            }
            else{
                bolinha.adicionarPosicao(0, 2);
                jButton5.setText("O");
                jButton12.setSelected(true);
                jButton13.setSelected(false);
            }
        }
        if(x.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 1 (X) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if(bolinha.verificarSeGanhou()){
            JOptionPane.showMessageDialog(null, "O Player 2 (O) ganhou!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
        if((!x.verificarSeGanhou()) && (!bolinha.verificarSeGanhou()) && (!jButton5.getText().equals("")) && (!jButton4.getText().equals(""))
                && (!jButton3.getText().equals("")) && (!jButton11.getText().equals("")) && (!jButton10.getText().equals(""))
                && (!jButton9.getText().equals("")) && (!jButton8.getText().equals("")) && (!jButton7.getText().equals(""))
                && (!jButton6.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "EMPATOU!\nLimpe o jogo caso queira continuar");
            jaAcabouAPartida = true;
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jButton5.setText("");
        jButton4.setText("");
        jButton3.setText("");
        jButton11.setText("");
        jButton10.setText("");
        jButton9.setText("");
        jButton8.setText("");
        jButton7.setText("");
        jButton6.setText("");
        jButton12.setSelected(true);
        jButton13.setSelected(false);
        x = new JogoDaVelha(false);
        bolinha = new JogoDaVelha(true);
        jaTeveAPrimeiraJogada = false;
        jaAcabouAPartida = false;
        JOptionPane.showMessageDialog(null, "O jogo foi reiniciado!");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaDoJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
