/*
Alunos:
    Pedro Veloso Inácio de Oliveira (20213004837)
    Pedro Vitor Melo Bitencourt (20213001540)
    Rafael Pereira Duarte (20213005146)

Colocamos um botão "Senha" extra para facilitar a correção e ver se está tudo certo
*/
package visao;

import java.awt.Color;
import javax.swing.JOptionPane;
import newpackage.JogoSenha;
public class JanelaJogo extends javax.swing.JFrame {
    
    private JogoSenha jogoSenha;
    public JanelaJogo() {
        jogoSenha = new JogoSenha();
        initComponents();
        jLabel7.setText("Voce ainda tem " + jogoSenha.getTentativas() + " tentativa(s)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Qual é a senha?");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("#");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel4.setText("@");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel5.setText("%");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel6.setText("&");

        jLabel7.setText("Você tem ainda 4 tentativa(s)");

        jButton1.setText("Tentar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Novo jogo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Sair");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Senha");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator3)))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(71, 71, 71)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean jaTirouUmaTentativa = false;
        
        /////////// Mensagens de aviso /////////////////////
        if(jTextField7.getText().length() > 1){
            JOptionPane.showMessageDialog(null, "Pode APENAS UM caracter por caixa de texto!");
            jTextField7.setText("");
        }
        if(((!jTextField7.getText().contains("*")) && (!jTextField7.getText().contains("#")) && (!jTextField7.getText().contains("@"))
                && (!jTextField7.getText().contains("%")) && (!jTextField7.getText().contains("&"))) && (jTextField7.getText().length() > 0)){
            JOptionPane.showMessageDialog(null, "Digite um caracter valido!");
            jTextField7.setText("");
        }
        
        if(jTextField6.getText().length() > 1){
            JOptionPane.showMessageDialog(null, "Pode APENAS UM caracter por caixa de texto!");
            jTextField6.setText("");
        }
        if(((!jTextField6.getText().contains("*")) && (!jTextField6.getText().contains("#")) && (!jTextField6.getText().contains("@"))
                && (!jTextField6.getText().contains("%")) && (!jTextField6.getText().contains("&"))) && (jTextField6.getText().length() > 0)){
            JOptionPane.showMessageDialog(null, "Digite um caracter valido!");
            jTextField6.setText("");
        }
        
        if(jTextField5.getText().length() > 1){
            JOptionPane.showMessageDialog(null, "Pode APENAS UM caracter por caixa de texto!");
            jTextField5.setText("");
        }
        if(((!jTextField5.getText().contains("*")) && (!jTextField5.getText().contains("#")) && (!jTextField5.getText().contains("@"))
                && (!jTextField5.getText().contains("%")) && (!jTextField5.getText().contains("&"))) && (jTextField5.getText().length() > 0)){
            JOptionPane.showMessageDialog(null, "Digite um caracter valido!");
            jTextField5.setText("");
        }
        
        if(jTextField4.getText().length() > 1){
            JOptionPane.showMessageDialog(null, "Pode APENAS UM caracter por caixa de texto!");
            jTextField4.setText("");
        }
        if(((!jTextField4.getText().contains("*")) && (!jTextField4.getText().contains("#")) && (!jTextField4.getText().contains("@"))
                && (!jTextField4.getText().contains("%")) && (!jTextField4.getText().contains("&"))) && (jTextField4.getText().length() > 0)){
            JOptionPane.showMessageDialog(null, "Digite um caracter valido!");
            jTextField4.setText("");
        }
        
        if(jTextField3.getText().length() > 1){
            JOptionPane.showMessageDialog(null, "Pode APENAS UM caracter por caixa de texto!");
            jTextField3.setText("");
        }
        if(((!jTextField3.getText().contains("*")) && (!jTextField3.getText().contains("#")) && (!jTextField3.getText().contains("@"))
                && (!jTextField3.getText().contains("%")) && (!jTextField3.getText().contains("&"))) && (jTextField3.getText().length() > 0)){
            JOptionPane.showMessageDialog(null, "Digite um caracter valido!");
            jTextField3.setText("");
        }
        
        if(jTextField2.getText().length() > 1){
            JOptionPane.showMessageDialog(null, "Pode APENAS UM caracter por caixa de texto!");
            jTextField2.setText("");
        }
        if(((!jTextField2.getText().contains("*")) && (!jTextField2.getText().contains("#")) && (!jTextField2.getText().contains("@"))
                && (!jTextField2.getText().contains("%")) && (!jTextField2.getText().contains("&"))) && (jTextField2.getText().length() > 0)){
            JOptionPane.showMessageDialog(null, "Digite um caracter valido!");
            jTextField2.setText("");
        }
        
        if(jTextField1.getText().length() > 1){
            JOptionPane.showMessageDialog(null, "Pode APENAS UM caracter por caixa de texto!");
            jTextField1.setText("");
        }
        if(((!jTextField1.getText().contains("*")) && (!jTextField1.getText().contains("#")) && (!jTextField1.getText().contains("@"))
                && (!jTextField1.getText().contains("%")) && (!jTextField1.getText().contains("&"))) && (jTextField1.getText().length() > 0)){
            JOptionPane.showMessageDialog(null, "Digite um caracter valido!");
            jTextField1.setText("");
        }
        //////////////////////////////////////////////////////////
        
        if((jTextField1.getText().length() == 1) && (jTextField2.getText().length() == 1) && (jTextField3.getText().length() == 1) &&
                (jTextField4.getText().length() == 1) && (jTextField5.getText().length() == 1) && (jTextField6.getText().length() == 1)
                && (jTextField7.getText().length() == 1) && (jogoSenha.getTentativas() > 0)){
            
            if(jogoSenha.getSenha().contains(jTextField1.getText()) && !(jogoSenha.verificarCaracterPosicao(jTextField1.getText(), 0))){
                jTextField1.setBackground(Color.CYAN);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            else if(jogoSenha.verificarCaracterPosicao(jTextField1.getText(), 0)){
                jTextField1.setBackground(Color.YELLOW);
            }
            else{
                jTextField2.setBackground(Color.WHITE);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            
            if(jogoSenha.getSenha().contains(jTextField2.getText()) && !(jogoSenha.verificarCaracterPosicao(jTextField2.getText(), 1))){
                jTextField2.setBackground(Color.CYAN);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            else if(jogoSenha.verificarCaracterPosicao(jTextField2.getText(), 1)){
                jTextField2.setBackground(Color.YELLOW);
            }
            else{
                jTextField2.setBackground(Color.WHITE);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            
            if(jogoSenha.getSenha().contains(jTextField3.getText()) && !(jogoSenha.verificarCaracterPosicao(jTextField3.getText(), 2))){
                jTextField3.setBackground(Color.CYAN);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            else if(jogoSenha.verificarCaracterPosicao(jTextField3.getText(), 2)){
                jTextField3.setBackground(Color.YELLOW);
            }
            else{
                jTextField3.setBackground(Color.WHITE);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            
            if(jogoSenha.getSenha().contains(jTextField4.getText()) && !(jogoSenha.verificarCaracterPosicao(jTextField4.getText(), 3))){
                jTextField4.setBackground(Color.CYAN);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            else if(jogoSenha.verificarCaracterPosicao(jTextField4.getText(), 3)){
                jTextField4.setBackground(Color.YELLOW);
            }
            else{
                jTextField4.setBackground(Color.WHITE);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            
            if(jogoSenha.getSenha().contains(jTextField5.getText()) && !(jogoSenha.verificarCaracterPosicao(jTextField5.getText(), 4))){
                jTextField5.setBackground(Color.CYAN);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            else if(jogoSenha.verificarCaracterPosicao(jTextField5.getText(), 4)){
                jTextField5.setBackground(Color.YELLOW);
            }
            else{
                jTextField5.setBackground(Color.WHITE);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            
            if(jogoSenha.getSenha().contains(jTextField6.getText()) && !(jogoSenha.verificarCaracterPosicao(jTextField6.getText(), 5))){
                jTextField6.setBackground(Color.CYAN);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            else if(jogoSenha.verificarCaracterPosicao(jTextField6.getText(), 5)){
                jTextField6.setBackground(Color.YELLOW);
            }
            else{
                jTextField6.setBackground(Color.WHITE);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            
            if(jogoSenha.getSenha().contains(jTextField7.getText()) && !(jogoSenha.verificarCaracterPosicao(jTextField7.getText(), 6))){
                jTextField7.setBackground(Color.CYAN);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
            else if(jogoSenha.verificarCaracterPosicao(jTextField7.getText(), 6)){
                jTextField7.setBackground(Color.YELLOW);
            }
            else{
                jTextField7.setBackground(Color.WHITE);
                if(jaTirouUmaTentativa == false){
                    jogoSenha.diminuirUmaTentativa();
                    jaTirouUmaTentativa = true;
                    jLabel7.setText("Voce tem ainda " + jogoSenha.getTentativas() + " tentativa(s)");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Todas caixas de texto têm que conter um caracter!!");
        }
        if(jogoSenha.getTentativas() == 0){
            JOptionPane.showMessageDialog(null, "Acabaram suas tentativas!\nA senha era " + jogoSenha.getSenha());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jogoSenha = new JogoSenha();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jLabel7.setText("Você tem " + jogoSenha.getTentativas() + " tentativa(s)");
        jTextField1.setBackground(Color.WHITE);
        jTextField2.setBackground(Color.WHITE);
        jTextField3.setBackground(Color.WHITE);
        jTextField4.setBackground(Color.WHITE);
        jTextField5.setBackground(Color.WHITE);
        jTextField6.setBackground(Color.WHITE);
        jTextField7.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "A senha é: " + jogoSenha.getSenha());
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
